### ISSUE TITLE
Chem.SanitizeMol "Can't kekulize mol" in calculate_outcomes

### ISSUE THREAD

**Issue by skinnider** [skinniderlab/CLM#256]
Getting a new error in `calculate_outcomes`. I wonder if it is related to #247? But at this point, all the SMILES that are getting passed into `calculate_outcomes` have been roundtripped through SMILES twice, via `tabulate_molecules`, right? 
In that case, since this is apparently an extremely rare failure mode (first time seeing this in now >100 runs of the pipeline, each with multiple `enum_factor`s), it may be reasonable to just catch this error and ignore that SMILES. 

```
[Sat Nov 30 21:57:19 2024]
rule calculate_outcomes:
    input: /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/structures_SMILES_2_unique_masses.csv.gz, /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/known_structures_SMILES_2_unique_masses.csv.gz, /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/invalid_structures_SMILES_2_unique_masses.csv.gz, /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/inputs/train0_structures_SMILES_2.smi
    output: /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/model_evaluation/100/structures_SMILES_2_calculate_outcomes.csv.gz
    jobid: 0
    reason: Forced execution
    wildcards: output_dir=/Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3, enum_factor=100, dataset=structures, repr=SMILES, fold=2
    resources: mem_mb=256000, mem_mib=244141, disk_mb=1000, disk_mib=954, tmpdir=/tmp, slurm_partition=main,hoppertest,skinniderlab, runtime=1000

reading NP model ...
model in
(INFO) (__main__.py) (30-Nov-24 21:57:26) CLM vsrc
(WARNING) (functions.py) (30-Nov-24 21:57:32) Not enough molecules for frequency bin '2-2'. Using 138249 molecules.
(WARNING) (functions.py) (30-Nov-24 21:57:32) Not enough molecules for frequency bin '3-10'. Using 128942 molecules.
(WARNING) (functions.py) (30-Nov-24 21:57:32) Not enough molecules for frequency bin '11-30'. Using 24713 molecules.
(WARNING) (functions.py) (30-Nov-24 21:57:32) Not enough molecules for frequency bin '31-100'. Using 10126 molecules.
(WARNING) (functions.py) (30-Nov-24 21:57:32) Not enough molecules for frequency bin '101-'. Using 17242 molecules.
(INFO) (calculate_outcomes.py) (30-Nov-24 21:57:33) Reading training smiles from /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/inputs/train0_structures_SMILES_2.smi
(INFO) (calculate_outcomes.py) (30-Nov-24 21:59:37) Reading sample smiles from                                                     smiles  ...     bin
0                Brc1cc(Br)c(Oc2c(Br)cc(Br)c(Br)c2Br)cc1Br  ...  31-100
1                  Brc1cc(Br)c(Oc2cc(Br)c(Br)cc2Br)c(Br)c1  ...    101-
2                    Brc1cc(Br)c(Oc2cc(Br)c(Br)cc2Br)cc1Br  ...  31-100
3                  Brc1cc(Br)c(Oc2cc(Br)cc(Br)c2Br)c(Br)c1  ...   11-30
4                      Brc1ccc(Oc2c(Br)cc(Br)cc2Br)c(Br)c1  ...  31-100
...                                                    ...  ...     ...
1319267  CCCCCCCCC=CCC=CCC=CCCCC(=O)OC(COC(=O)CCCCCCCCC...  ...     all
1319268    n1(C2C(O)C(O)C(O)C(CO)O2)c2c(NCC=C(CO)C)ncnc2n1  ...     all
1319269                 C1(C(C)C)c2c(c3oc(=O)ccc3ccc2OC)O1  ...     all
1319270     CC12CC(O)C(OC1=O)C13CC14CC(O)CC(C(=O)O)C4CCC23  ...     all
1319271                        C=CC=CC#CC(O)C=CCCCCCC(=O)O  ...     all

[1319272 rows x 5 columns]
 57%|█████▋    | 645702/1126343 [1:40:18<1:15:24, 106.24it/s][23:39:56] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[23:39:56] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[23:39:56] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[23:39:56] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[23:39:56] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
 90%|████████▉ | 1010784/1126343 [2:37:27<18:00, 106.99it/s]
Traceback (most recent call last):
  File "/Genomics/skinniderlab/PED-generation/env-clm/bin/clm", line 8, in <module>
    sys.exit(main())
  File "/Genomics/argo/users/ms0270/git/CLM/src/clm/__main__.py", line 81, in main
    args.func(args)
  File "/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py", line 346, in main
    calculate_outcomes(
  File "/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py", line 333, in calculate_outcomes
    train_df, sample_df = get_dataframes(train_file, prep_sample_df)
  File "/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py", line 157, in get_dataframes
    valid_data = prep_sample_df[prep_sample_df["is_valid"]].progress_apply(
  File "/Genomics/skinniderlab/PED-generation/env-clm/lib/python3.10/site-packages/tqdm/std.py", line 917, in inner
    return getattr(df, df_function)(wrapper, **kwargs)
  File "/Genomics/skinniderlab/PED-generation/env-clm/lib/python3.10/site-packages/pandas/core/frame.py", line 10374, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/Genomics/skinniderlab/PED-generation/env-clm/lib/python3.10/site-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
  File "/Genomics/skinniderlab/PED-generation/env-clm/lib/python3.10/site-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/Genomics/skinniderlab/PED-generation/env-clm/lib/python3.10/site-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
  File "/Genomics/skinniderlab/PED-generation/env-clm/lib/python3.10/site-packages/tqdm/std.py", line 912, in wrapper
    return func(*args, **kwargs)
  File "/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py", line 158, in <lambda>
    lambda x: smile_properties_dataframe(x, is_sample=True), axis=1
  File "/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py", line 103, in smile_properties_dataframe
    if (mol := clean_mol(a_row.smiles, raise_error=False)) is not None:
  File "/Genomics/argo/users/ms0270/git/CLM/src/clm/functions.py", line 52, in clean_mol
    Chem.SanitizeMol(mol)
rdkit.Chem.rdchem.KekulizeException: Can't kekulize mol.  Unkekulized atoms: 2 3 5 6 7 9 10 11 12 14 16 20 22 24 25 27 28 34 36
[Sun Dec  1 00:39:50 2024]
Error in rule calculate_outcomes:
    jobid: 0
    input: /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/structures_SMILES_2_unique_masses.csv.gz, /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/known_structures_SMILES_2_unique_masses.csv.gz, /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/invalid_structures_SMILES_2_unique_masses.csv.gz, /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/inputs/train0_structures_SMILES_2.smi
    output: /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/model_evaluation/100/structures_SMILES_2_calculate_outcomes.csv.gz
    conda-env: clm
    shell:
        clm calculate_outcomes --train_file /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/inputs/train0_structures_SMILES_2.smi --sampled_file /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/structures_SMILES_2_unique_masses.csv.gz --known_smiles_file /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/known_structures_SMILES_2_unique_masses.csv.gz --invalid_smiles_file /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/invalid_structures_SMILES_2_unique_masses.csv.gz --max_molecules 500000 --seed 12 --output_file /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/model_evaluation/100/structures_SMILES_2_calculate_outcomes.csv.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by skinnider** [comment]
Hmm, after pulling from master and re-running, this still seems to be causing an issue:

```
[Wed Dec  4 12:22:11 2024]
rule calculate_outcomes:
    input: /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/structures_SMILES_2_unique_masses.csv.gz, /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/known_structures_SMILES_2_unique_masses.csv.gz, /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/invalid_structures_SMILES_2_unique_masses.csv.gz, /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/inputs/train0_structures_SMILES_2.smi
    output: /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/model_evaluation/100/structures_SMILES_2_calculate_outcomes.csv.gz
    jobid: 0
    reason: Forced execution
    wildcards: output_dir=/Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3, enum_factor=100, dataset=structures, repr=SMILES, fold=2
    resources: mem_mb=256000, mem_mib=244141, disk_mb=1000, disk_mib=954, tmpdir=/tmp, slurm_partition=main,hoppertest,skinniderlab, runtime=1000

reading NP model ...
model in
(INFO) (__main__.py) (04-Dec-24 12:23:04) CLM vsrc
(WARNING) (functions.py) (04-Dec-24 12:23:09) Not enough molecules for frequency bin '2-2'. Using 138249 molecules.
(WARNING) (functions.py) (04-Dec-24 12:23:10) Not enough molecules for frequency bin '3-10'. Using 128942 molecules.
(WARNING) (functions.py) (04-Dec-24 12:23:10) Not enough molecules for frequency bin '11-30'. Using 24713 molecules.
(WARNING) (functions.py) (04-Dec-24 12:23:10) Not enough molecules for frequency bin '31-100'. Using 10126 molecules.
(WARNING) (functions.py) (04-Dec-24 12:23:10) Not enough molecules for frequency bin '101-'. Using 17242 molecules.
(INFO) (calculate_outcomes.py) (04-Dec-24 12:23:10) Reading training smiles from /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/inputs/train0_structures_SMILES_2.smi
(INFO) (calculate_outcomes.py) (04-Dec-24 12:24:31) Reading sample smiles from                                                     smiles  ...     bin
0                Brc1cc(Br)c(Oc2c(Br)cc(Br)c(Br)c2Br)cc1Br  ...  31-100
1                  Brc1cc(Br)c(Oc2cc(Br)c(Br)cc2Br)c(Br)c1  ...    101-
2                    Brc1cc(Br)c(Oc2cc(Br)c(Br)cc2Br)cc1Br  ...  31-100
3                  Brc1cc(Br)c(Oc2cc(Br)cc(Br)c2Br)c(Br)c1  ...   11-30
4                      Brc1ccc(Oc2c(Br)cc(Br)cc2Br)c(Br)c1  ...  31-100
...                                                    ...  ...     ...
1319267  CCCCCCCCC=CCC=CCC=CCCCC(=O)OC(COC(=O)CCCCCCCCC...  ...     all
1319268    n1(C2C(O)C(O)C(O)C(CO)O2)c2c(NCC=C(CO)C)ncnc2n1  ...     all
1319269                 C1(C(C)C)c2c(c3oc(=O)ccc3ccc2OC)O1  ...     all
1319270     CC12CC(O)C(OC1=O)C13CC14CC(O)CC(C(=O)O)C4CCC23  ...     all
1319271                        C=CC=CC#CC(O)C=CCCCCCC(=O)O  ...     all

[1319272 rows x 5 columns]
 57%|█████▋    | 645711/1126343 [1:05:36<48:09, 166.32it/s][13:30:07] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[13:30:07] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[13:30:07] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[13:30:07] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[13:30:07] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
100%|██████████| 1126343/1126343 [2:01:42<00:00, 154.24it/s]
/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  valid_df = pd.concat(valid_data.to_list())
/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  valid_df = pd.concat(valid_data.to_list())
/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  valid_df = pd.concat(valid_data.to_list())
/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  valid_df = pd.concat(valid_data.to_list())
/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  valid_df = pd.concat(valid_data.to_list())
/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  valid_df = pd.concat(valid_data.to_list())
/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  valid_df = pd.concat(valid_data.to_list())
/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  valid_df = pd.concat(valid_data.to_list())
/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  valid_df = pd.concat(valid_data.to_list())
/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  valid_df = pd.concat(valid_data.to_list())
(INFO) (calculate_outcomes.py) (04-Dec-24 14:36:11) 1126343 valid SMILES out of 1319272
(INFO) (calculate_outcomes.py) (04-Dec-24 14:36:11) 1296856 novel SMILES out of 1319272
(INFO) (calculate_outcomes.py) (04-Dec-24 14:36:43) Calculating outcomes
(INFO) (calculate_outcomes.py) (04-Dec-24 14:36:44) Calculating outcomes for bin 1-1
(INFO) (calculate_outcomes.py) (04-Dec-24 14:59:55) Calculating outcomes for bin 101-
(INFO) (calculate_outcomes.py) (04-Dec-24 15:01:18) Calculating outcomes for bin 11-30
(INFO) (calculate_outcomes.py) (04-Dec-24 15:03:14) Calculating outcomes for bin 2-2
(INFO) (calculate_outcomes.py) (04-Dec-24 15:11:25) Calculating outcomes for bin 3-10
(INFO) (calculate_outcomes.py) (04-Dec-24 15:19:07) Calculating outcomes for bin 31-100
(INFO) (calculate_outcomes.py) (04-Dec-24 15:20:16) Calculating outcomes for bin all
Traceback (most recent call last):
  File "/Genomics/skinniderlab/PED-generation/env-clm/bin/clm", line 8, in <module>
    sys.exit(main())
  File "/Genomics/argo/users/ms0270/git/CLM/src/clm/__main__.py", line 81, in main
    args.func(args)
  File "/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py", line 346, in main
    calculate_outcomes(
  File "/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py", line 336, in calculate_outcomes
    out = calculate_outcomes_dataframe(sample_df, train_df)
  File "/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py", line 292, in calculate_outcomes_dataframe
    if _out := handle_bin(
  File "/Genomics/argo/users/ms0270/git/CLM/src/clm/commands/calculate_outcomes.py", line 192, in handle_bin
    np.concatenate(bin_df["elements"].to_numpy()), return_counts=True
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 304592 has 0 dimension(s)
[Wed Dec  4 15:20:35 2024]
Error in rule calculate_outcomes:
    jobid: 0
    input: /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/structures_SMILES_2_unique_masses.csv.gz, /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/known_structures_SMILES_2_unique_masses.csv.gz, /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/invalid_structures_SMILES_2_unique_masses.csv.gz, /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/inputs/train0_structures_SMILES_2.smi
    output: /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/model_evaluation/100/structures_SMILES_2_calculate_outcomes.csv.gz
    conda-env: clm
    shell:
        clm calculate_outcomes --train_file /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/inputs/train0_structures_SMILES_2.smi --sampled_file /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/structures_SMILES_2_unique_masses.csv.gz --known_smiles_file /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/known_structures_SMILES_2_unique_masses.csv.gz --invalid_smiles_file /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/invalid_structures_SMILES_2_unique_masses.csv.gz --max_molecules 500000 --seed 12 --output_file /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/model_evaluation/100/structures_SMILES_2_calculate_outcomes.csv.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
srun: error: argo-40: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=6953435.0
[Wed Dec  4 15:20:35 2024]
Error in rule calculate_outcomes:
    jobid: 0
    input: /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/structures_SMILES_2_unique_masses.csv.gz, /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/known_structures_SMILES_2_unique_masses.csv.gz, /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/invalid_structures_SMILES_2_unique_masses.csv.gz, /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/inputs/train0_structures_SMILES_2.smi
    output: /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/model_evaluation/100/structures_SMILES_2_calculate_outcomes.csv.gz
    conda-env: clm
    shell:
        clm calculate_outcomes --train_file /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/inputs/train0_structures_SMILES_2.smi --sampled_file /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/structures_SMILES_2_unique_masses.csv.gz --known_smiles_file /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/known_structures_SMILES_2_unique_masses.csv.gz --invalid_smiles_file /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/100/prior/samples/invalid_structures_SMILES_2_unique_masses.csv.gz --max_molecules 500000 --seed 12 --output_file /Genomics/skinniderlab/food-clm/clm/database=FooDB-representation=rdkit-metric=tc-optimizer=facility_location-rarefaction=0.3/model_evaluation/100/structures_SMILES_2_calculate_outcomes.csv.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by anushka255** [comment]
This seems to be the same issue as #247. The exact row in `bin_df` causing this issue is 
```
('smiles', 'COc1=c-o-c2cc(O)c3c(c2)c(O)c(O)c2oc(=O)c-3=o-c(O)=c3c=2oc2c(O)c(=c32)-c(=O)-c(O)=c-1OC') ('is_valid', True) ('is_novel', True) ('size', 1) ('bin', 'all') ('canonical_smile', <NA>) ('elements', None) ('mws', <NA>) ('logp', <NA>) ('tcs', <NA>) ('tpsa', <NA>) ('qed', <NA>) ('rings1', <NA>) ('rings2', <NA>) ('rings3', <NA>) ('SA', <NA>) ('NP', <NA>) ('sp3', <NA>) ('rot', <NA>) ('stereo', <NA>) ('murcko', <NA>) ('donors', <NA>) ('acceptors', <NA>) ('fps', None)
```

The smiles is coming from 222503th line of `structures_SMILES_2_unique_masses.csv` file. The exact line is:
```
 CCYBQVKQJWRVLQ-UHFFFAOYSA-N,539.04618,C25H15O14,COc1=c-o-c2cc(O)c3c(c2)c(O)c(O)c2oc(=O)c-3=o-c(O)=c3c=2oc2c(O)c(=c32)-c(=O)-c(O)=c-1OC,1```

(Just making a note here, will investigate further).

**Comment by anushka255** [comment]
It appears that when the `clean_mol` function returns `None`, we fail to recognize the corresponding SMILES string as invalid. As a result, the downstream analysis proceeds with computations on this invalid input. To address this, we can either update the `is_valid` flag on the DataFrame based on the result of `clean_mol` . This can be done after line `106` in the section: https://github.com/skinniderlab/CLM/blob/17828b0e64667f813be2f29c98065ced38c849fb/src/clm/commands/calculate_outcomes.py#L103-L106

Or we can check the validity of SMILES based on nullity of `canonical_smiles`. Instead of using `bin_df = df[df["is_valid"]]`, we can filter the DataFrame with something like `df[~df['canonical_smiles'].isnull()]` in line `180`. https://github.com/skinniderlab/CLM/blob/17828b0e64667f813be2f29c98065ced38c849fb/src/clm/commands/calculate_outcomes.py#L176-L180
